// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBChJr7VG6eN2cEl3JnT4cKgRirSqFtcA',
    appId: '1:631268729695:web:bb531ddd5ea8e08ae8ccea',
    messagingSenderId: '631268729695',
    projectId: 'socialapp-f084d',
    authDomain: 'socialapp-f084d.firebaseapp.com',
    storageBucket: 'socialapp-f084d.appspot.com',
    measurementId: 'G-PK5L6F1XE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuMbb-AAbvYMEznL4YQbDdKfDiHcowKCM',
    appId: '1:631268729695:android:cfa3f4904040766ce8ccea',
    messagingSenderId: '631268729695',
    projectId: 'socialapp-f084d',
    storageBucket: 'socialapp-f084d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIuy-RoPpoUrvqvTt0Ib5zlj_UsEFNBu8',
    appId: '1:631268729695:ios:fa910cf10d5a9cb3e8ccea',
    messagingSenderId: '631268729695',
    projectId: 'socialapp-f084d',
    storageBucket: 'socialapp-f084d.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );
}
